#!/bin/sh

marker_file="/boot/plusultra"

if [ -e "$marker_file" ]; then
    echo "The script has already run on a previous boot. Exiting."
    exit 0
fi


#
#  P U L S E A U D I O  D E F A U L T  S A M P L E  R A T E
sudo sed -i 's/; default-sample-rate = 44100/default-sample-rate = 48000/' /etc/pulse/daemon.conf
sudo systemctl restart pulseaudio


#
#  S H A I R P O R T

# Get Tools and Libraries
sudo apt update
sudo apt -y upgrade
sudo apt -y install --no-install-recommends \
                build-essential git autoconf automake libtool \
                libpopt-dev libconfig-dev libasound2-dev avahi-daemon libavahi-client-dev libssl-dev libsoxr-dev \
                libplist-dev libsodium-dev libavutil-dev libavcodec-dev libavformat-dev uuid-dev libgcrypt-dev xxd \
                libpulse-dev

# Build and Install nqptp
git clone https://github.com/mikebrady/nqptp.git
cd nqptp
autoreconf -fi
./configure --with-systemd-startup
make
sudo make install
cd ..

# Enable and Start nqptp
sudo systemctl enable nqptp
sudo systemctl start nqptp

# Build and Install Shairport
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
autoreconf -fi
./configure --sysconfdir=/etc --with-pa \
    --with-soxr --with-avahi --with-ssl=openssl --with-systemd --with-airplay-2
make
sudo make install
cd ..


#
#  R A S P O T I F Y
curl -sL https://dtcooper.github.io/raspotify/install.sh | sh

# Set card for Raspotify to use
sudo sed -i "s\#LIBRESPOT_DEVICE=\"default\"\LIBRESPOT_DEVICE=\"pulse\"\g" /etc/raspotify/conf

# set Raspotify to use system wide PulseAudio
sudo sed -i '/\[Service\]/a\User=pulse' /lib/systemd/system/raspotify.service

sudo systemctl restart raspotify


#
#  R O O N  B R I D G E
curl -O https://download.roonlabs.net/builds/roonbridge-installer-linuxarmv7hf.sh
chmod +x roonbridge-installer-linuxarmv7hf.sh
yes Y | sudo ./roonbridge-installer-linuxarmv7hf.sh


sudo touch "$marker_file"
