#!/bin/sh

marker_file="/boot/plusultra"

if [ -e "$marker_file" ]; then
    echo "The script has already run on a previous boot. Exiting."
    exit 0
fi

#
#  P U L S E A U D I O  D E F A U L T  S A M P L E  R A T E
sudo sed -i 's/; default-sample-rate = 44100/default-sample-rate = 48000/' /etc/pulse/daemon.conf
sudo systemctl restart pulseaudio

sudo touch "$marker_file"
